name: Extract GCS credentials
inputs:
  VAULT_PASSWORD:
    description: "Vault password for decrypting credentials"
    required: true
runs:
  using: "composite"
  steps:
    # be careful with encrypt with old OpenSSL - https://habr.com/ru/post/535140/
    # openssl enc -base64 -aes-256-cbc -e -in test/integration/credentials.json -out test/integration/credentials.json.enc -md md5 -k ${VAULT_PASSWORD}
    - name: Decrypting credentials for Google Cloud Storage
      shell: "bash"
      id: secrets
      env:
        VAULT_PASSWORD: ${{ inputs.VAULT_PASSWORD }}
      run: |
        if [[ "" != "${VAULT_PASSWORD}" ]]; then
          openssl version
          openssl enc -base64 -aes-256-cbc -d -in test/integration/credentials.json.enc -out test/integration/credentials.json -md md5 -k ${VAULT_PASSWORD}
        fi
        echo "GCS_TESTS=$(if [ -z "${{ inputs.VAULT_PASSWORD }}" ]; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
